language: python
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
    - pypy
    - pypy3

install:
    - pip install -r dev_requirements.txt
    - pip install coveralls
script:
    py.test --cov-report term-missing --cov=modbus -v tests/
after_success:
    coveralls
