language: python
python:
    - 3.8
    - 3.7
    - 3.6
    - 3.5
    - 3.4
    - 2.7

install:
    - pip install -r dev_requirements.txt
    - pip install coveralls
script:
    py.test --cov-report term-missing --cov=umodbus -v tests/
after_success:
    coveralls
